# QA {#qa}

>
> Essence of Quality: to do no harm and to make things better. - Eric Klein 
> 

Why QA is important?

- The impact on clinical trials: analysis of RTOG 9704 study of pancreatic cancer showed that per protocol (PP) was associated with the lower tumor control rate is correlated with decreased risk of failure (p = 0.016) 

[Uncertainties in Radiation Medicine: An Oncologist's Perspective](https://vimeo.com/76862861)
CTV margin for subclinical tumor - ML

[Medical physics practice guideline 4.a](https://aapm.onlinelibrary.wiley.com/doi/full/10.1120/jacmp.v16i3.5431)

## Patient-specific QA

At CC, we do PSQA using 2D ion-chamber array and EPID.

*Question: compared to film/chamber, what are the limitations of EPID-based QA?*

- not true composite (TC)?
- 

*What are the action limit and tolerance limit at CC?*

*For EPID-based QA, how do you make sure the physical properties (sag, position, ...) of imager are still in tolerance?* 

- `IsoCal` Calibration

## Quality and safety 

[AAPM quality and safety sources](https://www.aapm.org/QualitySafety/default.asp)


## TG-100

## TG-275

2017 AAPM Spring Clinical meeting [Best Practices for Physics Plan and Chart Review: Report of AAPM Task Group 275](https://www.aapm.org/education/sams/Default.asp?v=true&mid=127&qid=2573)

According to Marks, the effectiveness of strategy in preventing error propagation is automation, checklist, and training (from most effective to least effective)

