# SBRT {#sbrt}

> The great difficulty in the world is not for people to accept new ideas, but to make them forget about old ideas. -John Maynard Keynes

ACR/ASTRO definition of SBRT: an external beam radiation therapy method used to very precisely deliver a high dose of radiation to an extracranial target within the body, using either a single dose or a small number of fractions.

The chapter follows the review paper [Stereotactic Body Radiation Therapy
A Comprehensive Review](https://journals.lww.com/amjclinicaloncology/fulltext/2007/12000/Stereotactic_Body_Radiation_Therapy__A.12.aspx#R5-12) by Brian K. Chang and Robert Timmerman

## History

- 1951 [Lars Leksell](https://en.wikipedia.org/wiki/Lars_Leksell) developed a frame exclusively for human beings;
- 1991 Lax and Blomgren developed the frist sterotactic body frame with abdominal compression
- 1994 Hamilton et al. linac-based spine radiosurgery
- 1999 [Shirato et al](https://www.sciencedirect.com/science/article/pii/S014067369900700X?via%3Dihub) developed a real-time tumor-tracking radiotherapy system where the location of the tumor was detected every 0.03 seconds with a reported accuracy of 1 mm.
- [Uematsu et al](https://www.ncbi.nlm.nih.gov/pubmed/9506350) investigated a frameless stereotactic approach using a unit consisting of a Linac, x-ray simulator, CT scanner, and table. The patients performed shallow respiration with an oxygen mask, and tumor motion was monitored with an x-ray simulator. When tumor motion was within an acceptable range the table was rotated to the CT for positioning, and then finally rotated to the Linac for treatment delivery.

## Radiobiology of Albative Fractionation


The <font color="Salmon">linear-quadratic (LQ)</font> model assumes 2 components of cell killing by radiation,

$$
S = e - \alpha  D - \beta D^2
$$
According to this equation, the cell survival curve
continuously bends. This is in contrast to experimental observations that describe a final straight line after 7 or more
decades of cell killing.?

Further work to understand the underlying biologic mechanisms of SBRT, in particular the implications of **dose rate**, **treatment delivery times** (<font color="Red">Long treatment time $\rightarrow$ less cell killing opposite to FLASH?</font>)), and **target dose heterogeneity** (<font color="Red">What are the best ways to evaluate heterogeneity besides HI?</font>), will be necessary for us to optimize our use of this approach. Future clinical studies should carefully document these variables to allow a more accurate comparison of prescribed doses between reported experiences. Additional efforts to develop accurate models of cell survival at high doses per fraction may also aid in providing us with a guideline for dose optimization

## Technical Aspects of SBRT

### Immobilization and Target Motion Issues Related to SBRT

There are essentially 2 approaches to account for tumor
motion: minimization of target motion via immobilization
(eg, abdominal compression or breath hold techniques), or
alternatively to account for physiologic tumor motion via
tracking or gating.

  

[^eddy]: 
The frame has Teflon insulators to prevent <font color="Salmon">eddy currents</font> during MRI scans, which caused mild to moderate skin burns before. 

<p class='FOO'> During CT or MR simulation, does the frame have to been perfectly leveled?
</p>



<p class='FOO'> During stereotactic localization, you identify the indicator marker on CT or MR axial scans. how does this process tell the system where is origin and where is the isocenter?
</p>

As part of the imaging process, it is essential to provide exact points of reference by means of which the shape and position of the targets can be ascertained with respect to the patient’s skull. Moreover, during the subsequent radiosurgery session, the head of the patient must be entirely immobilized to maintain the accuracy of the shots.

### Stereotactic reference 

- use an indicator box during image acquisition
- use the CBCT (only available for [Icon](https://www.youtube.com/watch?v=ZeFFwkxnoME))


### Steps to create new plan

- Creat a new patient file
    - Have to complete the **Radiological Examination** field
- Plan | New Plan to make a new treatment plan
- Open a patient file
Tomographic imaging acq



The recommended doses can be found [here](http://www.aboutcancer.com/gk_doses.htm). The dose typically depends on the tumor size (the smaller the tumor, the higher the prescription dose). 

`a) wrong; c) wrong; Rhabdomyosarcoma is mostly treated with linac.`

## Dose fall-off

Currently higher X-ray, $\gamma$-ray, and protons  are used to treat SRS/SRT. 

`a); d)`

SRS treatment are characterized by steep dose gradients, for example, >50%/cm, at the target periphery. If the spatial accuracy of the treatment delivery is $\pm$ 1 mm, the dosimetric uncertainty in this region will be >50%/cm times 1 mm, which equals to >5%/cm. 

`d)`

`b); c)`

## Required measurements for commissioning a SRS/SBRT program
The measurements required for commissioning a SRS/SRT program are similar to conventional external beam radiotherapy with the exception of transmission measurement which is typically very small due to the construction of the cone collimator. 

`a); c); d)`

` b) is wrong as the average energy from Co-60 sources is 1.25 MeV not 6 MV; c) is wrong because sources move in the translational mode; d) is wrong because the Gamma knife is more accurate than a linac-based SRS system. `

[Mindermann (2015) Gamma Knife, CyberKnife or micro-multileaf collimator LINAC for intracranial radiosurgery?](https://link.springer.com/article/10.1007/s00701-014-2275-6), is a good read. The author questioned a few dosimetric studies in comparing several delivery systems, and stated that the questions of dosimetry needs to be answered, which include: the source of the photon radiation (cobalt-60 or linear accelerator); the nature of the collimators (fixed aperture, iris, micro-multileaf, etc.); moving or stationary radiation sources during beam-off time or beam-on time; the fixation of the head; the planning software; the imagery used; the way the images are acquired (dedicated protocols, head fixation, etc.); the number of beams; the number of arrival angles; the exit dose; the scatter factor of a given beam; the distance source to target; the time period over which a dose is delivered; the system's overall accuracy; dose rates; the nature and the size of the lesion; the shape of the lesion; its proximity to organs at risk; the experience and the neurosurgical and anatomical knowhow of the radiosurgeon.

The SRS treatments have been delivered using GK, CK, tomotherapy machines, and linacs (Lutz _et al._ (1987))[^lutz]. 

To simulate the head frame used in the SRS, a body frame was used in early SBRT treatments (Sweden and Japan) in early 1990s. With advances of technologies, however, most current SBRT treatments do not use body frames , because the localization accuracy is comparable between frame-based and frameless SBRT and worse than that in the SRS. 

[^lutz]:
[A system for stereotactic radiosurgery with a linear accelerator](https://www.ncbi.nlm.nih.gov/pubmed/3276655).
Extensive performance tests have shown that a target, localized by CT, can be irradiated with a positional accuracy of __2.4 mm__ in any direction with 95% confidence. This number has not been decreased much in last 30 years. The geometric accuracy of isocenter localization of $\pm1$ mm is acceptable. 



SBRT prostate using spacer [spaceoar.com](https://www.spaceoar.com/physicians/clinical-publications/)

