# IGRT {#igrt}

**References**

TG-76 (2006) The management of respiratory motion in Radiation Oncology

Several publications about QA issues associated with image-guided radiation therapy

* TG-58 (2001) Clinical use of electronic portal imaging
    + Planar MV
* TG-142 (2009): QA of medical accelerators
    + planar kV and MV; kV- and MV-CBCT
* TG-104 (2009): The Role of In-Room kV X-Ray Imaging for Patient setup and Target Localization
    + Planar kV and kV-CBCT
* TG-148 (2010) QA for helical Tomotherapy
    + Fan beam MVCT
* TG-154 (2011) QA of US-guided External beam radiotherapy for prostate cancer
* TG-135 (2011): QA for Robotic Radiosurgry
    + planar kV
* TG-179 (2012): QA for image-guided radiation therapy utilizing CT-based technologies
    + kV- and MV-CBCT; fan beam kVCT and MVCT 
* TG-147 (2012): QA for nonradiographic RT localization and positioning systems
* Jaffrey (2012) Assuring safety and quality in image-guided delivery of RT

## Cyber Knife
A linear accelerator in CyberKnife generates a 6 MV x-ray beam. The microwave frequency it uses for accelerating electrons is in the range of:  a) 500 to 1,000 MHz b) 2 to 4 GHz c) 8 to 12 GHz d) 15-20 GHz 

## TG 180

2016 AAPM Annual Meeting [TG180: Image Guidance Doses Delivered During RT](https://www.aapm.org/education/sams/Default.asp?v=true&mid=115&qid=2396)

- recommends a dose threshold beyond which imaging dose be accounted
for: **5% of therapeutic target dose**

### MV imaging

- EPID: 1 - 5 cGy/pair of orthogonal portals
- MVCT (TOMO): 1 - 3 cGy typical
- MV-CBCT: 2- 12 cGy typical

### kV imaging

- kV DR: 0.1 - 1.0 cGy/pair of orthogonal beams
- kV-CBCT: Soft tissue: 0.1 - 3 cGy/acquisition; Bone: 0.3 - 6 cGy/acquisition; D~bone~ is about 2-4 times D~{soft tissue}~
- kV-CBCT(4D): differs from (3D), depends on protocol used


### Comparison

- SNR: kV > 2.5 MV > 6 MV; kV images provide best image quality per unit dose
- The 2.5 MV beam had excellent contrast at a lower dose than 6 MV and may be superior to kV for difficult to image areas that include large changes in anatomical thickness. Varain 2.5 MV (Nitsch P, Robertson D, Balter P, Med Phys 42, 3266 (2015))

(Radiation dose from kilovoltage cone beam computed tomography in an image-guided radiotherapy procedure," Int J Radiat Oncol Biol Phys, vol. 73, pp. 610-7, 2009) Doses to radiosensitive organs can total **300 cGy** accrued over an entire treatment course if kV CBCT scans are acquired daily.